export enum CategoryProduct {
	HAMBURGUESAS = 'HAMBURGUESAS',
	SALCHIPAPAS = 'SALCHIPAPAS',
	POLLO_BROASTER = 'POLLO_BROASTER',
	ALITAS = 'ALITAS',
	TWISTER = 'TWISTER',
	COMBO = 'COMBO',
	REFRESCOS = 'REFRESCOS',
	FROZEN = 'FROZEN',
	CREMOSOS = 'CREMOSOS',
	BATIDOS = 'BATIDOS',
	JUGOS = 'JUGOS',
	CLASICOS = 'CLASICOS',
	GASEOSAS = 'GASEOSAS',
	PIDELO_CON_CHAUFA = 'PIDELO_CON_CHAUFA',
}

export enum Status {
	ACTIVE = 'ACTIVE',
	INACTIVE = 'INACTIVE',
}

export enum TicketStatus {
	COMPLETED = 'COMPLETED',
	PROCESS = 'PROCESS',
	CANCELLED = 'CANCELLED',
}

export enum TicketType {
	TABLE = 'TABLE',
	DELIVERY = 'DELIVERY',
	PICKUP = 'PICKUP',
}

export enum DeliveryStatus {
	COMPLETED = 'COMPLETED',
	PROCESS = 'PROCESS',
	CANCELLED = 'CANCELLED',
}

export enum PaymentType {
	YAPE = 'YAPE',
	PLIN = 'PLIN',
	EFECTIVO = 'EFECTIVO',
}
